const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{Teclado: 0},
	{fundo: 0},
	{Sólido: 0},
	{chão: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{jogador: 0},
	{caixa: 0},
	{terra1: 0},
	{terra3: 0},
	{terra2: 0},
	{Partículas: 0},
	{caveira: 0},
	{Senóide: 0},
	{inimigo: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{FonteDeSprites: 0},
	{Tvidas: 0},
	{tvida: 0},
	{tcoleta: 0},
	{estado: 0},
	{caveiras: 0},
	{pontos: 0},
	{vidas: 0}
];

self.InstanceType = {
	Teclado: class extends self.IInstance {},
	fundo: class extends self.ITiledBackgroundInstance {},
	chão: class extends self.ITiledBackgroundInstance {},
	jogador: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	terra1: class extends self.ISpriteInstance {},
	terra3: class extends self.ISpriteInstance {},
	terra2: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	caveira: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Tvidas: class extends self.ITextInputInstance {},
	tvida: class extends self.ITextInstance {},
	tcoleta: class extends self.ITextInstance {}
}